// this header is auto-generated by CMake

#pragma once

#include "caf/detail/log_level.hpp"

#define CAF_LOG_LEVEL CAF_LOG_LEVEL_QUIET

/* #undef CAF_ENABLE_RUNTIME_CHECKS */

#define CAF_ENABLE_EXCEPTIONS

/* #undef CAF_ENABLE_ACTOR_PROFILER */
